In [52]:
import numpy as np

In [53]:
array = np.array([1, 22, 3, 53, 7, 10])

In [54]:
print(array)
print(array.ndim)
print(array[1])
print(array[0: 3])
print(type(array))
print(array.shape)

[ 1 22  3 53  7 10]
1
22
[ 1 22  3]
<class 'numpy.ndarray'>
(6,)


In [55]:
array_index = [0, 3, 5]
array[array_index]

array([ 1, 53, 10])

![array_numpy](../images/array_numpy.png)

In [56]:
array_2D = np.array([[1, 2, 3], [4, 5, 6]])

In [57]:
print(array_2D)
print(array_2D.ndim)
print(type(array_2D))
print(array_2D.shape)

[[1 2 3]
 [4 5 6]]
2
<class 'numpy.ndarray'>
(2, 3)


In [58]:
print(array_2D.size)
print(array_2D[1, 1])
print(array_2D[0, 2])
print(array_2D[0, 0])
print(array_2D[0:2, 2])
print(array_2D[1])
print(array_2D[1])

6
5
3
1
[3 6]
[4 5 6]
[4 5 6]


In [59]:
array_2D[1, 2] = 10
print(array_2D)

[[ 1  2  3]
 [ 4  5 10]]


In [60]:
array_3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [61]:
print(array_3D)
print(array_3D.ndim)
print(type(array_3D))
print(array_3D.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
<class 'numpy.ndarray'>
(2, 2, 3)


In [62]:
print(array_3D.size)
print(array_3D[1, 1])
print(array_3D[0, 0])
print(array_3D[1, 0, 2])
print(array_3D[1, 1, 0:2])
print(array_3D[1])

12
[10 11 12]
[1 2 3]
9
[10 11]
[[ 7  8  9]
 [10 11 12]]


In [63]:
array_3D[1, 1, 2] = 20
print(array_3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 20]]]


In [64]:
import time

In [65]:
array_test = range(1, 1000000)

start_time = time.time()

sum = 0
for i in array_test:
  sum += i

end_time = time.time()

print(f"A soma total é: {sum}")
print(f"Tempo total de {(end_time - start_time) * 1000:.2f} milissegundos")

A soma total é: 499999500000
Tempo total de 239.59 milissegundos


In [66]:
array_numpy = np.arange(1, 1000000)
print(array_numpy.dtype)

array_numpy_int64 = array_numpy.astype(np.int64)
print(array_numpy_int64.dtype)

start_time = time.time()

sum_numpy = np.sum(array_numpy_int64)

end_time = time.time()

print(f"A soma total é: {sum_numpy}")
print(f"Tempo total de {(end_time - start_time) * 1000:.2f} milissegundos")

int32
int64
A soma total é: 499999500000
Tempo total de 1.00 milissegundos
