In [2]:
import numpy as np

In [3]:
array = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
print(array)
print(type(array))
print(array.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [5]:
matrix = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
print(matrix)
print(type(matrix))
print(matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
(3, 3)


In [14]:
print(matrix.size)
print(matrix[1, 2])
print(matrix[2, 1])
print(matrix[0, 0])
print(matrix[0:2, 2])
print(matrix[2])


9
6
8
1
[[3]
 [6]]
[[7 8 9]]


In [15]:
matrix[2, 2] = 10
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
